### ISSUE TITLE
The last update time is Feb 25, 2020 of the ZH website, is there anything wrong?

### ISSUE THREAD

**Issue by leviding** [javascript-tutorial/zh.javascript.info#627]
@iliakan The last update time is Feb 25, 2020 of https://zh.javascript.info , is there anything wrong?

As shown in the picture below:

<img width="1073" alt="Screen Shot 2020-03-01 at 5 55 22 PM" src="https://user-images.githubusercontent.com/26959437/75623543-e7a1cb00-5be5-11ea-9e0f-a30af8f77056.png">

**Comment by iliakan** [comment]
@leviding You mean auto-updates do not happen?

**Comment by leviding** [comment]
@iliakan Auto-updates goes well, just the Date in this picture is not updated.

**Comment by leviding** [comment]
@iliakan  There have a bug of task 5: https://zh.javascript.info/bind#tasks

<img width="881" alt="Screen Shot 2020-03-02 at 3 51 41 PM" src="https://user-images.githubusercontent.com/26959437/75655897-c8ff0b00-5c9d-11ea-871b-768620d1cfc1.png">

**Comment by iliakan** [comment]
This one took me a while to debug!

The reason was: `task.md` used `\r\n` as linebreaks instead of `\n`.

That's caused by a person on Windows and misconfigured git. There's `.gitattributes` with `* text=auto eol=lf` that tells git to use `\n`, so right now I can't imagine how that happened.

I fixed the repo. Please use `\n` as line breaks.

**Comment by leviding** [comment]
@iliakan Get it. Thanks a lot!

**Comment by iliakan** [comment]
Date update also fixed, thanks for bringing it into attention!

**Comment by leviding** [comment]
Thanks again!
